name: messenger_chat_head
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dash_bubble: ^2.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_overlay_window: ^0.4.5
  get: ^4.6.6
  intl: ^0.19.0
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/messenger_logo.png"  # Your uploaded file
  adaptive_icon_background: "#3F51B5"  # Indigo background
  adaptive_icon_foreground: "assets/logos/messenger_logo.png"

  

flutter:
  uses-material-design: true
  assets:
    - assets/profilepic/
    - assets/lottie/
